---
all:
  children:
    script_factory_windows:
      hosts:
        un-001:
          ansible_host: 192.0.2.11
          script_factory_un_id: un-001
          script_factory_run_as_user: DOMAIN\un-001-worker
          script_factory_browser_path: C:\Users\un-001-worker\AppData\Local\Yandex\YandexBrowser\Application\browser.exe
        un-002:
          ansible_host: 192.0.2.12
          script_factory_un_id: un-002
          script_factory_run_as_user: DOMAIN\un-002-worker
          script_factory_browser_path: C:\Users\un-002-worker\AppData\Local\Yandex\YandexBrowser\Application\browser.exe
      vars:
        ansible_connection: winrm
        ansible_port: 5986
        ansible_winrm_scheme: https
        ansible_winrm_transport: kerberos
        ansible_winrm_server_cert_validation: validate
        ansible_user: "{{ vault_ansible_user }}"
        ansible_password: "{{ vault_ansible_password }}"
